version: '3'

services:
  postgres:
    container_name: rd-postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - rd-network

  fastapi:
    container_name: rd-fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - static_volume:/app/frontend/static
    env_file:
      - .env
    networks:
      - rd-network
    depends_on:
      - postgres
    ports:
      - "8000:8000"


volumes:
  database:
  static_volume:

networks:
  rd-network:
    driver: bridge
